# Generated by Django 3.1.7 on 2021-03-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvmodel',
            name='csv_continents',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='iso_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='locations',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='new_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='new_cases_per_million',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='new_cases_smoothed_per_million',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='new_deaths_per_million',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='new_deaths_smoothed_per_million',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='total_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='total_cases_per_million',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='total_deaths_per_million',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
