# Generated by Django 3.1.7 on 2021-03-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210305_0753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvmodel',
            old_name='csv_continents',
            new_name='continent',
        ),
        migrations.RenameField(
            model_name='csvmodel',
            old_name='locations',
            new_name='location',
        ),
        migrations.AddField(
            model_name='csvmodel',
            name='new_cases_smoothed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csvmodel',
            name='new_deaths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csvmodel',
            name='new_deaths_smoothed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csvmodel',
            name='total_deaths',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
